#!/usr/bin/env python3
"""
Regenerate encoding/cards/DISTRIBUTION.md by scanning every .ccgnf file
under encoding/cards/ and counting rarity-by-faction.

Called by the card-cluster skill after each approved cluster; can also
be invoked manually after hand-editing card files.

Usage:
    python3 tools/update-card-distribution.py
    make card-distribution     (wrapped)
"""
from __future__ import annotations

import datetime as dt
import re
import sys
from pathlib import Path


MONO_FACTIONS = ["EMBER", "BULWARK", "TIDE", "THORN", "HOLLOW"]
RARITIES = ["C", "U", "R", "M"]


def parse_cards(path: Path) -> list[dict]:
    """Extract (factions, rarity) for every Card declaration in a file."""
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    # Split at the start of each Card declaration. Naive but fine for the
    # current flat, one-card-per-block convention used in encoding/cards/*.
    chunks = re.split(r"(?=^Card\s+\S+)", text, flags=re.MULTILINE)
    out = []
    for chunk in chunks:
        if not chunk.lstrip().startswith("Card"):
            continue
        fm = re.search(r"factions:\s*\{([^}]+)\}", chunk)
        rm = re.search(r"rarity:\s*([CURM])\b", chunk)
        if not fm or not rm:
            continue
        factions = [f.strip() for f in fm.group(1).split(",")]
        out.append({"factions": factions, "rarity": rm.group(1)})
    return out


def pct(n: int, d: int) -> str:
    if d == 0:
        return "—"
    return f"{(n * 100) / d:.1f}%"


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    cards_dir = repo_root / "encoding" / "cards"
    out_path = cards_dir / "DISTRIBUTION.md"

    # Gather per-file card info.
    mono = {f: {r: 0 for r in RARITIES} for f in MONO_FACTIONS}
    for faction in MONO_FACTIONS:
        file = cards_dir / f"{faction.lower()}.ccgnf"
        for card in parse_cards(file):
            mono[faction][card["rarity"]] += 1

    # Dual: parse dual.ccgnf and group by pair.
    dual_counts: dict[tuple[str, ...], dict[str, int]] = {}
    dual_order: list[tuple[str, ...]] = []
    for card in parse_cards(cards_dir / "dual.ccgnf"):
        pair = tuple(sorted(card["factions"]))
        if pair not in dual_counts:
            dual_counts[pair] = {r: 0 for r in RARITIES}
            dual_order.append(pair)
        dual_counts[pair][card["rarity"]] += 1

    # Neutral
    neutral_counts = {r: 0 for r in RARITIES}
    for card in parse_cards(cards_dir / "neutral.ccgnf"):
        neutral_counts[card["rarity"]] += 1

    # Totals per rarity
    def mono_total(r: str) -> int:
        return sum(mono[f][r] for f in MONO_FACTIONS)

    def dual_total(r: str) -> int:
        return sum(pair[r] for pair in dual_counts.values())

    rarity_totals = {
        r: mono_total(r) + dual_total(r) + neutral_counts[r] for r in RARITIES
    }
    grand_total = sum(rarity_totals.values())

    # Emit markdown
    lines: list[str] = []
    lines.append("# Resonance — Card Set Distribution")
    lines.append("")
    lines.append(
        "*Regenerated by `tools/update-card-distribution.py` "
        "(wrapped as `make card-distribution`) and by the `card-cluster` "
        "skill after each approved cluster.*"
    )
    lines.append("")
    lines.append("Target (per `design/Supplement.md §4`, for a 250-card set):")
    lines.append("")
    lines.append("- Common:   44% (110 cards)")
    lines.append("- Uncommon: 32% (80 cards)")
    lines.append("- Rare:     18% (45 cards)")
    lines.append("- Mythic:    6% (15 cards)")
    lines.append("")
    lines.append("## Current counts — mono-faction")
    lines.append("")
    lines.append("| Faction  | C | U | R | M | Total |")
    lines.append("|----------|---|---|---|---|-------|")
    for faction in MONO_FACTIONS:
        row = mono[faction]
        tot = sum(row.values())
        lines.append(
            f"| {faction:<8} | {row['C']} | {row['U']} | {row['R']} | {row['M']} |   {tot}   |"
        )

    lines.append("")
    if dual_order:
        lines.append("## Dual-faction")
        lines.append("")
        lines.append("| Pair         | C | U | R | M | Total |")
        lines.append("|--------------|---|---|---|---|-------|")
        for pair in dual_order:
            counts = dual_counts[pair]
            tot = sum(counts.values())
            label = "/".join(pair)
            lines.append(
                f"| {label:<12} | {counts['C']} | {counts['U']} | {counts['R']} | {counts['M']} |   {tot}   |"
            )
        lines.append("")

    lines.append("## Neutral")
    lines.append("")
    lines.append("| Rarity | Count |")
    lines.append("|--------|-------|")
    for r in RARITIES:
        lines.append(f"| {r}      |   {neutral_counts[r]}   |")
    lines.append("")

    lines.append("## Totals")
    lines.append("")
    lines.append("| Rarity | Mono | Dual | Neutral | Total | Target | Actual |")
    lines.append("|--------|------|------|---------|-------|--------|--------|")
    target_share = {"C": "44%", "U": "32%", "R": "18%", "M": "6%"}
    for r in RARITIES:
        mt = mono_total(r)
        dt_ = dual_total(r)
        nt = neutral_counts[r]
        total = rarity_totals[r]
        lines.append(
            f"| {r}      | {mt:>4} | {dt_:>4} | {nt:>7} | {total:>5} | {target_share[r]:<6} | {pct(total, grand_total):<6} |"
        )
    lines.append("")
    lines.append(f"**Grand total: {grand_total} cards.**")
    lines.append("")
    lines.append(f"Last updated: {dt.datetime.now(dt.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path.relative_to(repo_root)} ({grand_total} cards)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
